// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASW_FfIITQdQjuppQzazGreivrmUMhfYY',
    appId: '1:803548605147:web:e9b76ac7245af36afc3afe',
    messagingSenderId: '803548605147',
    projectId: 'dash-7cdea',
    authDomain: 'dash-7cdea.firebaseapp.com',
    storageBucket: 'dash-7cdea.firebasestorage.app',
    measurementId: 'G-4K1DW6V3G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8anDd8ASoz9zr6oZ_DUwPQMiELVSxjE',
    appId: '1:803548605147:android:56b4527846fde72efc3afe',
    messagingSenderId: '803548605147',
    projectId: 'dash-7cdea',
    storageBucket: 'dash-7cdea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA5YltJJPDOXSTXQnllXax1f_lPjD7HLc',
    appId: '1:803548605147:ios:74d84545d76abe6afc3afe',
    messagingSenderId: '803548605147',
    projectId: 'dash-7cdea',
    storageBucket: 'dash-7cdea.firebasestorage.app',
    androidClientId: '803548605147-l7daf84ndtf9k4bk2sdkkgfb4o7evp57.apps.googleusercontent.com',
    iosClientId: '803548605147-7j3nosaj6kmsekr43jv1jin4tp0h8lvj.apps.googleusercontent.com',
    iosBundleId: 'com.dash.mobile.yunsoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASW_FfIITQdQjuppQzazGreivrmUMhfYY',
    appId: '1:803548605147:web:10b42bcafe1e73ecfc3afe',
    messagingSenderId: '803548605147',
    projectId: 'dash-7cdea',
    authDomain: 'dash-7cdea.firebaseapp.com',
    storageBucket: 'dash-7cdea.firebasestorage.app',
    measurementId: 'G-8SRDXCF9E7',
  );

}